In [1]:
import pandas as pd

In [2]:
df_wl_name = pd.read_csv("file_data\\수위_관측소.csv")

In [90]:
df_pp_name = pd.read_csv("file_data\\강수량_관측소_api.csv")

In [94]:
df_wl_name.head(45)

,Unnamed: 0,station_code,station_name,address,etc_address,longitude,latitude,zero_elevation,warning_wl,alarm_wl,pfh,location
0,97,1007604,안성시(한평교),경기도 안성시 일죽면,고은리 한평교,127-26-01,37-06-24,76.169,6.0,7.0,8.65,"[127.43361111111112, 37.10666666666667]"
1,98,1007605,이천시(장호원교),경기도 이천시,장호원읍 장호원리 장호원교,127-38-07,37-06-54,56.683,4.0,5.0,5.60,"[127.63527777777779, 37.115]"
2,100,1007615,여주시(원부교),경기도 여주시,점동면 원부리 원부교,127-38-03,37-09-45,50.945,5.5,6.5,8.69,"[127.63416666666667, 37.1625]"
3,101,1007617,여주시(삼합교),경기도 여주시,점동면 삼합리 삼합교,127-43-09,37-12-08,42.076,5.5,7.0,8.26,"[127.71916666666667, 37.202222222222225]"
4,102,1007620,여주시(강천리),경기도 여주시,강천면 강천리 546-1,127-42-50,37-13-52,38.400,6.0,8.0,9.92,"[127.71388888888889, 37.23111111111111]"
5,103,1007625,여주시(남한강교),경기도 여주시,우만동 99-5(구)남한강교,127-40-51,37-15-17,36.292,6.5,8.5,10.32,"[127.68083333333334, 37.25472222222222]"
6,104,1007630,남한강,경기도 여주군,강천면 이호리,127-41-12,37-10-59,NaN,NaN,NaN,NaN,"[127.68666666666667, 37.183055555555555]"
7,105,1007633,강천보(상류),경기도,여주시 단현동 47-3천,127-41-00,37-16-23,0.000,42.5,43.5,45.11,"[127.68333333333334, 37.27305555555555]"
8,106,1007634,강천보(하류),경기도,여주시 강천면 이호리 523-2,127-41-05,37-17-01,0.000,NaN,NaN,44.25,"[127.68472222222222, 37.28361111111111]"
9,107,1007635,여주시(여주대교),경기도 여주시,상동 여주대교,127-38-51,37-17-46,32.529,6.0,8.0,9.19,"[127.64750000000001, 37.29611111111111]"
10,108,1007639,여주보(상류),경기도,여주시 대신면 천남리 680,127-36-56,37-19-34,0.000,37.0,38.5,39.70,"[127.61555555555555, 37.32611111111112]"
11,109,1007640,여주시(율극교),경기도 여주시,흥천면 율극리 율극교,127-34-23,37-20-02,32.057,4.5,5.5,7.19,"[127.57305555555556, 37.33388888888889]"
12,110,1007641,여주보(하류),경기도,여주시 능서면 왕대리 1008천,127-36-12,37-19-43,0.000,NaN,NaN,39.20,"[127.60333333333332, 37.328611111111115]"
13,111,1007645,이천시(복하교),경기도 이천시,부발읍 신하리 복하교,127-27-39,37-16-01,46.418,3.0,3.5,4.29,"[127.46083333333334, 37.26694444444444]"
14,112,1007649,흑천,경기도 양평군,양평읍 원덕리,127-32-35,37-27-51,NaN,NaN,NaN,NaN,"[127.54305555555555, 37.46416666666667]"
15,113,1007650,여주시(흥천대교),경기도 여주시,흥천면 다대리 흥천대교,127-32-06,37-19-59,33.536,3.5,4.5,5.40,"[127.535, 37.33305555555556]"
16,114,1007653,대평,경기도 양평군 지평면,대평리 742,127-37-47,37-25-21,NaN,NaN,NaN,NaN,"[127.62972222222221, 37.4225]"
17,115,1007655,여주시(양촌교),경기도 여주시,대신면 초현리 양촌교,127-33-45,37-22-57,30.136,4.5,5.5,6.96,"[127.5625, 37.3825]"
18,116,1007656,여주저류지,경기도 여주시 대신면,당남리 318,127-32-59,37-22-52,0.000,NaN,NaN,NaN,"[127.54972222222221, 37.38111111111111]"
19,117,1007660,여주시(이포대교),경기도 여주시,금사면 이포리 이포대교,127-32-15,37-24-04,26.105,6.5,8.5,NaN,"[127.5375, 37.401111111111106]"
20,118,1007662,이포보(상류),경기도,여주시 금사면 이포리 375 이포대교,127-32-16,37-24-04,0.000,33.0,34.5,36.39,"[127.53777777777778, 37.401111111111106]"
21,119,1007664,이포보(하류),경기도,여주시 대신면 천서리 674,127-32-29,37-24-30,0.000,NaN,NaN,36.09,"[127.54138888888889, 37.40833333333333]"
22,120,1007672,금사,경기도 여주군 금사면,장흥리 40,127-29-20,37-23-19,NaN,NaN,NaN,NaN,"[127.4888888888889, 37.38861111111111]"
23,121,1007680,양평군(흑천교),경기도 양평군,개군면 공세리 흑천교,127-31-39,37-27-58,32.286,3.0,3.5,4.57,"[127.5275, 37.46611111111111]"
24,122,1007685,양평군(양평교),경기도 양평군,양평읍 양근리 양평교,127-29-24,37-29-11,19.558,9.0,11.0,13.60,"[127.49, 37.48638888888889]"
25,123,1007690,양평군(봉상교),경기도 양평군,단월면 봉상리 봉상교,127-39-04,37-30-42,78.780,3.0,4.0,4.51,"[127.65111111111112, 37.51166666666666]"
26,124,1007697,양평군(신원리),경기도 양평군 양서면,신원리 504-14 신원리제방,127-22-18,37-31-29,24.290,4.0,5.0,6.02,"[127.37166666666666, 37.52472222222222]"
27,161,1013620,목동교,경기도 가평군,북면 목동리,127-32-54,37-52-59,98.689,NaN,NaN,NaN,"[127.54833333333333, 37.88305555555556]"
28,165,1013652,가평천,경기도 가평군,북면 개곡리,127-31-40,37-52-29,NaN,NaN,NaN,NaN,"[127.52777777777777, 37.874722222222225]"
29,166,1013655,가평군(가평교),경기도 가평군,가평읍 읍내리 가평교,127-31-05,37-49-53,51.857,3.0,4.0,5.18,"[127.51805555555555, 37.831388888888895]"
30,177,1015630,산장제1교,경기도 가평군,상면 덕현리,127-24-37,37-45-18,58.960,NaN,NaN,NaN,"[127.41027777777778, 37.755]"
31,178,1015639,청평댐,경기도 가평군,설악면 유명로 2630,127-25-28,37-43-15,NaN,NaN,NaN,NaN,"[127.42444444444445, 37.72083333333334]"
32,179,1015640,가평군(청평댐),경기도 가평군,설악면 회곡리 745-27 청평댐,127-25-21,37-43-24,0.670,NaN,NaN,51.33,"[127.4225, 37.723333333333336]"
33,180,1015644,가평군(청평교),경기도 가평군,청평면 청평리 청평교,127-24-53,37-44-02,31.222,4.5,5.5,8.59,"[127.41472222222222, 37.73388888888889]"
34,181,1015645,가평군(신청평대교),경기도 가평군,청평면 삼회리 산90 신청평대교인근,127-24-36,37-43-05,22.612,10.0,12.5,15.46,"[127.41000000000001, 37.71805555555556]"
35,182,1015680,남양주시(삼봉리),경기도 남양주시,조안면 삼봉리 235-1,127-20-21,37-35-44,24.422,4.5,6.0,7.25,"[127.33916666666666, 37.595555555555556]"
36,183,1016607,용인시(월촌교),경기도 용인시,처인구 모현면 갈담리 월촌교,127-14-21,37-19-56,49.553,4.5,5.0,6.71,"[127.23916666666666, 37.33222222222223]"
37,184,1016650,광주시(경안교),경기도 광주시,쌍령동 경안교,127-15-47,37-24-23,34.106,4.0,5.0,6.13,"[127.26305555555555, 37.406388888888884]"
38,185,1016655,경안교,경기도 광주시,오포읍 양벌리,127-15-06,37-23-33,35.616,NaN,NaN,NaN,"[127.25166666666667, 37.3925]"
39,186,1016660,광주시(섬뜰교),경기도 광주시,초월읍 도평리 섬뜰교,127-17-34,37-23-57,36.123,4.0,5.0,6.41,"[127.29277777777777, 37.399166666666666]"
40,187,1016670,광주시(서하교),경기도 광주시,초월읍 서하리 서하교,127-18-29,37-25-44,26.762,4.5,5.5,5.92,"[127.30805555555555, 37.428888888888885]"
41,188,1016695,광주시(광동교),경기도 광주시,퇴촌면 광동리 광동교,127-17-39,37-28-17,-0.057,27.0,27.5,28.35,"[127.29416666666667, 37.47138888888889]"
42,189,1017678,팔당댐,경기도 남양주시,조안면 다산로 320,127-17-05,37-31-30,NaN,NaN,NaN,NaN,"[127.28472222222221, 37.525]"
43,190,1017690,남양주시(팔당댐),경기도 남양주시,조안면 능내리 팔당댐,127-17-00,37-31-38,0.009,NaN,NaN,24.51,"[127.28333333333333, 37.52722222222222]"
44,191,1018605,고안(등록문화재),경기도 남양주시 조안면,능내리 825,127-15-00,37-32-30,10.000,0.0,0.0,NaN,"[127.25, 37.541666666666664]"

In [50]:
df_wl_name['longitude'][0].split('-')
list0 = df_wl_name['longitude'][1].split('-')
DD = DD = int(list0[0]) + int(list0[1])/60 + int(list0[2])/3600
DD

127.63527777777779

In [98]:
loc_list_wl = []
loc_list_pp = []

In [64]:
#위도경도 변환 함수

#위경도 변환 DD = Degree(앞 3자리) + Minutes(중간 2자리)/60 + Seconds/3600

def location(x,i: int,list_name):
    list0 = str(x['longitude'][i]).split('-')
    list1 = str(x['latitude'][i]).split('-')
    DD1 = int(list0[0]) + int(list0[1])/60 + int(list0[2])/3600
    DD2 = int(list1[0]) + int(list1[1])/60 + int(list1[2])/3600
    list_name.append([DD1,DD2])

In [99]:
for i in range(0, len(df_wl_name)):
    location(df_wl_name,i, loc_list_wl)

In [100]:
loc_list_wl

[[127.43361111111112, 37.10666666666667],
 [127.63527777777779, 37.115],
 [127.63416666666667, 37.1625],
 [127.71916666666667, 37.202222222222225],
 [127.71388888888889, 37.23111111111111],
 [127.68083333333334, 37.25472222222222],
 [127.68666666666667, 37.183055555555555],
 [127.68333333333334, 37.27305555555555],
 [127.68472222222222, 37.28361111111111],
 [127.64750000000001, 37.29611111111111],
 [127.61555555555555, 37.32611111111112],
 [127.57305555555556, 37.33388888888889],
 [127.60333333333332, 37.328611111111115],
 [127.46083333333334, 37.26694444444444],
 [127.54305555555555, 37.46416666666667],
 [127.535, 37.33305555555556],
 [127.62972222222221, 37.4225],
 [127.5625, 37.3825],
 [127.54972222222221, 37.38111111111111],
 [127.5375, 37.401111111111106],
 [127.53777777777778, 37.401111111111106],
 [127.54138888888889, 37.40833333333333],
 [127.4888888888889, 37.38861111111111],
 [127.5275, 37.46611111111111],
 [127.49, 37.48638888888889],
 [127.65111111111112, 37.51166666666666],
 [127.37166666666666, 37.52472222222222],
 [127.54833333333333, 37.88305555555556],
 [127.52777777777777, 37.874722222222225],
 [127.51805555555555, 37.831388888888895],
 [127.41027777777778, 37.755],
 [127.42444444444445, 37.72083333333334],
 [127.4225, 37.723333333333336],
 [127.41472222222222, 37.73388888888889],
 [127.41000000000001, 37.71805555555556],
 [127.33916666666666, 37.595555555555556],
 [127.23916666666666, 37.33222222222223],
 [127.26305555555555, 37.406388888888884],
 [127.25166666666667, 37.3925],
 [127.29277777777777, 37.399166666666666],
 [127.30805555555555, 37.428888888888885],
 [127.29416666666667, 37.47138888888889],
 [127.28472222222221, 37.525],
 [127.28333333333333, 37.52722222222222],
 [127.25, 37.541666666666664],
 [127.23916666666666, 37.5475],
 [127.24138888888889, 37.544444444444444],
 [127.19555555555556, 37.74027777777778],
 [127.18361111111112, 37.70944444444445],
 [127.16472222222222, 37.69166666666666],
 [126.81055555555555, 37.59861111111111],
 [127.15194444444445, 37.65],
 [127.14361111111111, 37.64527777777778],
 [127.15, 37.60388888888889],
 [127.11055555555555, 37.54555555555555],
 [127.07805555555555, 37.524166666666666],
 [127.10833333333333, 37.37],
 [127.12249999999999, 37.46888888888889],
 [127.07444444444444, 37.49805555555556],
 [127.06388888888888, 37.519444444444446],
 [127.0625, 37.52305555555555],
 [127.05, 37.53333333333333],
 [127.05333333333333, 37.737500000000004],
 [127.05388888888889, 37.65277777777778],
 [127.05, 37.62416666666667],
 [127.07055555555556, 37.5925],
 [126.99472222222222, 37.51611111111111],
 [126.95666666666666, 37.51444444444444],
 [126.95, 37.516666666666666],
 [126.90305555555557, 37.40472222222222],
 [126.8938888888889, 37.452222222222225],
 [126.84583333333333, 37.47888888888889],
 [126.87416666666665, 37.50833333333333],
 [126.76055555555556, 37.53194444444444],
 [126.81055555555555, 37.59861111111111],
 [126.79333333333334, 37.602222222222224],
 [126.79333333333334, 37.602222222222224],
 [126.79333333333334, 37.602222222222224],
 [126.75972222222222, 37.52305555555555],
 [126.76138888888889, 37.541666666666664],
 [126.74638888888889, 37.57333333333334],
 [126.75888888888889, 37.574444444444445],
 [126.75944444444444, 37.574444444444445],
 [126.77222222222223, 37.583333333333336],
 [126.78277777777778, 37.58972222222222],
 [126.66416666666667, 37.69583333333333],
 [126.76138888888889, 37.76027777777778],
 [126.96055555555556, 38.11083333333333],
 [127.01583333333333, 38.105000000000004],
 [127.00777777777778, 38.08972222222222],
 [127.0175, 38.05638888888888],
 [127.27166666666666, 38.12416666666667],
 [127.22055555555556, 38.09],
 [127.20583333333333, 38.06527777777777],
 [127.13083333333333, 38.0625],
 [127.12916666666666, 38.06083333333333],
 [127.23583333333333, 38.00222222222222],
 [127.21416666666667, 38.010555555555555],
 [127.14277777777778, 38.01777777777777],
 [127.13805555555557, 38.02305555555555],
 [127.07222222222222, 38.08722222222222],
 [127.10444444444444, 38.03666666666666],
 [127.10388888888889, 38.03611111111111],
 [127.0761111111111, 38.03138888888889],
 [127.05083333333333, 37.88],
 [127.07666666666667, 37.99277777777778],
 [127.05611111111111, 38.00888888888889],
 [126.98333333333333, 38.026944444444446],
 [126.91888888888889, 37.984722222222224],
 [126.87805555555555, 38.00277777777778],
 [126.74194444444444, 37.90416666666667],
 [126.78388888888888, 37.821111111111115],
 [127.02027777777778, 37.2175],
 [127.32888888888888, 36.9975],
 [127.26777777777778, 37.00222222222222],
 [127.27194444444444, 37.08166666666667],
 [127.18277777777779, 36.97361111111111],
 [127.18444444444445, 37.11027777777778],
 [127.08, 36.98361111111111],
 [127.06, 37.135],
 [126.99972222222222, 37.12361111111111],
 [127.05194444444444, 37.095],
 [127.02888888888889, 37.096111111111114],
 [126.9975, 37.052499999999995],
 [127.01666666666667, 37.016666666666666],
 [127.03361111111111, 36.97805555555556],
 [126.97583333333334, 36.96805555555556],
 [127.0, 36.93333333333333],
 [126.92805555555556, 36.980000000000004],
 [126.92805555555556, 36.980000000000004],
 [126.52222222222223, 37.731944444444444],
 [126.60416666666666, 37.56111111111111],
 [126.60305555555556, 37.56055555555555],
 [126.60138888888888, 37.56027777777778],
 [126.60277777777777, 37.56111111111111],
 [126.875, 37.348333333333336],
 [126.85694444444444, 37.32277777777778],
 [126.8, 37.00055555555556]]

In [69]:
### 강수량 관측소 위도 경도가 없는 값들이 있어서 오류가 나기 때문에 dropna
df_pp_name.dropna()

,Unnamed: 0,station_code,agency_name,station_name,address,etc_address,longitude,latitude
0,0,10014010,환경부,평창군(월정분교),강원도 평창군,진부면 내동산길 4 진부초등학교 월정분교(폐교),128-35-56,37-42-34
1,1,10014020,환경부,정선군(정선군2청사),강원도 정선군,정선읍 녹송4길 71 정선군 제2청사,128-40-24,37-23-04
2,2,10014070,환경부,상원사,강원도 평창군 진부면,동산 오대산장,128-34-46,37-45-43
3,3,10014080,환경부,강릉시(대기리),강원도 강릉시,왕산면 대기리 2810천,128-46-36,37-35-30
4,4,10014090,환경부,정선군(고한읍사무소),강원도 정선군,고한읍 고한2길 1 고한읍사무소,128-51-08,37-12-13
...,...,...,...,...,...,...,...,...
726,726,51014090,환경부,강진군(석교교),전라남도 강진군,군동면 석교리 석교교 상류,126-48-59,34-38-10
727,727,51014100,환경부,장흥군(별천교),전라남도 장흥군,부산면 금자리 별천교 하류,126-54-22,34-43-53
728,728,51014150,환경부,병영,전라남도 강진군 병영면,병영면사무소 내,126-49-09,34-42-52
729,729,53024010,환경부,목포,전라남도 목포시 유달동,서산국교,126-23-00,34-47-00
730,730,99999999,한국수자원공사,평림댐,전라남도 장성군,삼계면 수옥리 762-3,126-40-15,35-18-14

In [101]:
for i in range(0, len(df_pp_name)):
    location(df_pp_name,i, loc_list_pp)

In [102]:
loc_list_pp

[[127.75138888888888, 37.42444444444444],
 [127.49, 37.48638888888889],
 [127.61666666666666, 37.016666666666666],
 [127.64805555555556, 37.29527777777778],
 [127.71055555555556, 37.55638888888888],
 [127.44305555555556, 37.276944444444446],
 [127.60555555555555, 37.1975],
 [127.37444444444444, 37.07666666666667],
 [127.5275, 37.145833333333336],
 [127.67944444444444, 37.39722222222222],
 [127.3461111111111, 37.53111111111111],
 [127.43972222222223, 37.401944444444446],
 [127.54305555555555, 37.46416666666667],
 [127.68666666666667, 37.183055555555555],
 [127.51805555555555, 37.831388888888895],
 [127.56611111111111, 37.921388888888885],
 [127.54833333333333, 37.88305555555556],
 [127.52777777777777, 37.874722222222225],
 [127.3536111111111, 37.81777777777778],
 [127.39666666666668, 37.71277777777778],
 [127.4775, 37.59277777777778],
 [127.42055555555557, 37.72277777777778],
 [127.41027777777778, 37.755],
 [127.25472222222223, 37.42944444444444],
 [127.18611111111112, 37.47805555555556],
 [127.22, 37.28111111111111],
 [127.24527777777777, 37.20277777777778],
 [127.24277777777777, 37.32972222222222],
 [127.28388888888888, 37.231388888888894],
 [127.18694444444445, 37.23361111111111],
 [127.25166666666667, 37.3925],
 [127.26305555555555, 37.406388888888884],
 [127.28333333333333, 37.52722222222222],
 [127.04638888888888, 37.74472222222222],
 [127.22833333333334, 37.78611111111111],
 [126.94416666666667, 37.344722222222224],
 [127.05083333333333, 37.39277777777778],
 [127.25, 37.541666666666664],
 [127.21166666666667, 37.63583333333333],
 [126.96666666666667, 37.53333333333333],
 [126.8875, 37.495],
 [126.90305555555557, 37.40472222222222],
 [127.12249999999999, 37.46888888888889],
 [127.15194444444445, 37.65],
 [127.21138888888889, 37.79111111111111],
 [127.05166666666666, 37.702222222222225],
 [127.06916666666666, 37.361666666666665],
 [127.05555555555556, 37.552499999999995],
 [126.9875, 37.42333333333333],
 [126.8125, 37.47944444444445],
 [126.94555555555556, 37.35305555555556],
 [127.15138888888889, 37.45138888888889],
 [127.08583333333333, 37.67472222222222],
 [127.05, 37.62416666666667],
 [126.98805555555556, 37.388888888888886],
 [127.19, 37.725833333333334],
 [127.11777777777777, 37.337500000000006],
 [127.28333333333333, 37.52722222222222],
 [126.71555555555555, 37.61527777777778],
 [126.76722222222222, 37.56916666666667],
 [126.79916666666666, 37.6],
 [127.11277777777777, 38.06527777777777],
 [127.07527777777777, 38.13527777777778],
 [127.0175, 38.05638888888888],
 [126.98666666666666, 38.11638888888889],
 [127.02111111111111, 38.103611111111114],
 [127.27166666666666, 38.12416666666667],
 [127.21638888888889, 38.00944444444445],
 [127.33638888888889, 38.00805555555556],
 [127.00527777777778, 37.91083333333333],
 [127.13111111111111, 37.96361111111111],
 [127.14333333333335, 37.830000000000005],
 [127.28527777777778, 37.90222222222222],
 [126.74194444444444, 37.90416666666667],
 [126.87972222222221, 37.856944444444444],
 [126.85194444444444, 37.780833333333334],
 [126.85777777777777, 37.92861111111111],
 [127.09027777777777, 37.09916666666667],
 [127.27888888888889, 37.00805555555556],
 [127.31305555555555, 37.16611111111111],
 [126.94611111111111, 37.081944444444446],
 [126.97972222222222, 37.21027777777778],
 [127.02888888888889, 37.096111111111114],
 [127.08, 36.98361111111111],
 [127.09388888888888, 37.226111111111116],
 [127.19583333333334, 37.141666666666666],
 [127.20333333333333, 37.02916666666667],
 [127.26305555555555, 36.94472222222222],
 [127.00416666666666, 37.98777777777778],
 [126.61833333333333, 37.56388888888888],
 [126.86444444444444, 37.31222222222222],
 [126.88083333333333, 37.350833333333334]]

In [103]:
len(loc_list_pp)

92

In [95]:
## 새 column으로 붙여주기

df_wl_name['location'] = loc_list_wl

ValueError: Length of values (920) does not match length of index (92)

In [104]:
df_pp_name['location'] = loc_list_pp

In [97]:
df_pp_name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    92 non-null     int64
 1   station_code  92 non-null     int64
 2   agency_name   92 non-null     object
 3   station_name  92 non-null     object
 4   address       92 non-null     object
 5   etc_address   91 non-null     object
 6   longitude     92 non-null     object
 7   latitude      92 non-null     object
dtypes: int64(2), object(6)
memory usage: 5.9+ KB

In [107]:
### 거리 구해서 가장 가까운 관측소를 매칭해주기

!pip install haversine

Collecting haversine
  Downloading haversine-2.2.0-py2.py3-none-any.whl (4.9 kB)
Installing collected packages: haversine
Successfully installed haversine-2.2.0

WARNING: You are using pip version 20.2; however, version 20.2.2 is available.
You should consider upgrading via the 'c:\anaconda3\python.exe -m pip install --upgrade pip' command.

In [108]:
from haversine import haversine

In [110]:
#둥근 구를 가정하고 두 지점 사이의 거리를 구해줌
haversine([45.7595,4.8222],[48.8567, 2.3508])

391.51795422752934

# 수위 관측소와 가장 가까운 강수량 관측소 찾기
수위 관측소의 각 위치(df_wl_name['location'])마다 df_pp_name['location'] 전체와의 거리 차이를 구한다. 거리 차이가 가장 작은 관측소 코드를 'pp_station_code'라는 변수로 설정하여 수위 데이터에 추가한다.

In [144]:
pp_station = []

def closest_station(x):
    for i in range(0,len(df_wl_name)):
        min_index = 0
        for j in range(0,len(df_pp_name)):
            a = haversine(df_wl_name['location'][i],df_pp_name['location'][j])
            if j == 0:
                min_dist = a
            else:
                if a<=min_dist:
                    min_dist= a
                    min_index = j
        pp_station.append(df_pp_name['station_code'][min_index])

In [145]:
closest_station(df_wl_name)

In [146]:
pp_station

[10074080,
 10074070,
 10074070,
 10074175,
 10074175,
 10074030,
 10074175,
 10074030,
 10074030,
 10074030,
 10074030,
 10074030,
 10074030,
 10074060,
 10074170,
 10074170,
 10074100,
 10074170,
 10074170,
 10074170,
 10074170,
 10074170,
 10074120,
 10074170,
 10074010,
 10074040,
 10074110,
 10134045,
 10134140,
 10134020,
 10154035,
 10154032,
 10154032,
 10154032,
 10154032,
 10074110,
 10164050,
 10164080,
 10164075,
 10164080,
 10164080,
 10184232,
 10184232,
 10184232,
 10184050,
 10184050,
 10184050,
 10184220,
 10184220,
 10184110,
 10194030,
 10184110,
 10184110,
 10184110,
 10184100,
 10184140,
 10184230,
 10184100,
 10184140,
 10184140,
 10184140,
 10184140,
 10184010,
 10184200,
 10184200,
 10184200,
 10184070,
 10184070,
 10184070,
 10184090,
 10184080,
 10184160,
 10184080,
 10194020,
 10194030,
 10194030,
 10194030,
 10194030,
 10194020,
 10194020,
 10194020,
 10194020,
 10194020,
 10194020,
 10194030,
 10194010,
 10234010,
 10214020,
 10214030,
 10214030,
 10214010,
 10224010,
 10224020,
 10224020,
 10204010,
 10204010,
 10224020,
 10224020,
 10224060,
 10204010,
 10204020,
 10204010,
 10204010,
 10204010,
 10224050,
 10204010,
 10214010,
 11014140,
 10234040,
 10234040,
 10234010,
 10234010,
 11014060,
 11014020,
 11014020,
 11014020,
 11014120,
 11014100,
 11014080,
 11014010,
 11014070,
 11014070,
 11014070,
 11014070,
 11014070,
 11014080,
 11014040,
 11014080,
 11014040,
 11014040,
 12014010,
 12014010,
 12014010,
 12014010,
 12014010,
 12024020,
 12024010,
 11014040]

In [147]:
len(pp_station)

138

In [151]:
df_wl_name.head(10)

,Unnamed: 0,station_code,station_name,address,etc_address,longitude,latitude,zero_elevation,warning_wl,alarm_wl,pfh,location,pp_station
0,97,1007604,안성시(한평교),경기도 안성시 일죽면,고은리 한평교,127-26-01,37-06-24,76.169,6.0,7.0,8.65,"[127.43361111111112, 37.10666666666667]",10074080
1,98,1007605,이천시(장호원교),경기도 이천시,장호원읍 장호원리 장호원교,127-38-07,37-06-54,56.683,4.0,5.0,5.60,"[127.63527777777779, 37.115]",10074070
2,100,1007615,여주시(원부교),경기도 여주시,점동면 원부리 원부교,127-38-03,37-09-45,50.945,5.5,6.5,8.69,"[127.63416666666667, 37.1625]",10074070
3,101,1007617,여주시(삼합교),경기도 여주시,점동면 삼합리 삼합교,127-43-09,37-12-08,42.076,5.5,7.0,8.26,"[127.71916666666667, 37.202222222222225]",10074175
4,102,1007620,여주시(강천리),경기도 여주시,강천면 강천리 546-1,127-42-50,37-13-52,38.400,6.0,8.0,9.92,"[127.71388888888889, 37.23111111111111]",10074175
5,103,1007625,여주시(남한강교),경기도 여주시,우만동 99-5(구)남한강교,127-40-51,37-15-17,36.292,6.5,8.5,10.32,"[127.68083333333334, 37.25472222222222]",10074030
6,104,1007630,남한강,경기도 여주군,강천면 이호리,127-41-12,37-10-59,NaN,NaN,NaN,NaN,"[127.68666666666667, 37.183055555555555]",10074175
7,105,1007633,강천보(상류),경기도,여주시 단현동 47-3천,127-41-00,37-16-23,0.000,42.5,43.5,45.11,"[127.68333333333334, 37.27305555555555]",10074030
8,106,1007634,강천보(하류),경기도,여주시 강천면 이호리 523-2,127-41-05,37-17-01,0.000,NaN,NaN,44.25,"[127.68472222222222, 37.28361111111111]",10074030
9,107,1007635,여주시(여주대교),경기도 여주시,상동 여주대교,127-38-51,37-17-46,32.529,6.0,8.0,9.19,"[127.64750000000001, 37.29611111111111]",10074030

In [ ]:
df_wl_name.to_csv("수위데이터-관측소 merge")